# Generated by Django 4.2.6 on 2023-10-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=520)),
                ('reciver', models.CharField(max_length=520)),
                ('action', models.JSONField()),
                ('message', models.CharField(max_length=520)),
                ('label', models.CharField(max_length=520)),
                ('signiture', models.CharField(max_length=520)),
            ],
        ),
    ]
