# Generated by Django 4.2.6 on 2023-10-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txn',
            old_name='reciver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='txn',
            old_name='signiture',
            new_name='signature',
        ),
    ]
